apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag
  template:
    metadata:
      labels:
        app: flag
    spec:
      containers:
      - image: okteto.dev/flag:latest
        name: flag
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/RECIPES-html.zip"
        - name: Vless_UUID
          value: "7266a8c1-fb44-4cb3-8949-907fe2bdca43"
        - name: Vless_Path
          value: "/7266a8c1-fb44-4cb3-8949-907fe2bdca43-vless"
        - name: Vmess_UUID
          value: "7266a8c1-fb44-4cb3-8949-907fe2bdca43"
        - name: Vmess_Path
          value: "/7266a8c1-fb44-4cb3-8949-907fe2bdca43-vmess"
        - name: Share_Path
          value: "/v2link"
