apiVersion: apps/v1
kind: Deployment
metadata:
  name: look
spec:
  replicas: 1
  selector:
    matchLabels:
      app: look
  template:
    metadata:
      labels:
        app: look
    spec:
      containers:
      - image: okteto.dev/look:latest
        name: look
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/wulabing/3DCEList/archive/master.zip"
        - name: Vless_UUID
          value: "a2717860-6ae8-4a60-9c0e-2d10d26d4b30"
        - name: Vless_Path
          value: "/a2717860-6ae8-4a60-9c0e-2d10d26d4b30-vless"
        - name: Vmess_UUID
          value: "a2717860-6ae8-4a60-9c0e-2d10d26d4b30"
        - name: Vmess_Path
          value: "/a2717860-6ae8-4a60-9c0e-2d10d26d4b30-vmess"
        - name: Share_Path
          value: "/v2link"
